# ==============================
# APPLICATION URL
# ==============================
url=https://silhouettedesignstore.com/

# ==============================
# USER CREDENTIALS
# ==============================
username=priti.kasar@magnetoitsolutions.com
password=Priti@123

fakeusername=fakeusertest@gmail.com
fakepassword=abc@12345

# ==============================
# BROWSER CONFIG
# Options:
# chrome
# chrome-headless
# firefox
# firefox-headless
# edge
# ==============================
browser=chrome-headless

# ==============================
# TIMEOUTS (SECONDS)
# ==============================
implicit.wait=10
page.load.timeout=30